config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :losers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loser.rb
# frozen_string_literal: true

class Loser < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/losers_controller.rb
# frozen_string_literal: true

class LosersController < ApplicationController
  before_action :set_loser, only: [:show, :edit, :update, :destroy]

  # GET /losers
  # GET /losers.json
  def index
    @losers = Loser.all
  end

  # GET /losers/1
  # GET /losers/1.json
  def show
  end

  # GET /losers/new
  def new
    @loser = Loser.new
  end

  # GET /losers/1/edit
  def edit
  end

  # POST /losers
  # POST /losers.json
  def create
    @loser = Loser.new(loser_params)

    respond_to do |format|
      if @loser.save
        format.html { redirect_to @loser, notice: "Loser was successfully created." }
        format.json { render :show, status: :created, location: @loser }
      else
        format.html { render :new }
        format.json { render json: @loser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /losers/1
  # PATCH/PUT /losers/1.json
  def update
    respond_to do |format|
      if @loser.update(loser_params)
        format.html { redirect_to @loser, notice: "Loser was successfully updated." }
        format.json { render :show, status: :ok, location: @loser }
      else
        format.html { render :edit }
        format.json { render json: @loser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /losers/1
  # DELETE /losers/1.json
  def destroy
    @loser.destroy
    respond_to do |format|
      format.html { redirect_to losers_url, notice: "Loser was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loser
      @loser = Loser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loser_params
      params.require(:loser).permit(:vorname, :nachname)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/losers_helper.rb
# frozen_string_literal: true

module LosersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConcourseAssignment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/losers/_form.html.erb
<%= form_with(model: loser, local: true) do |form| %>
  <% if loser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loser.errors.count, "error") %> prohibited this loser from being saved:</h2>

      <ul>
      <% loser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vorname %>
    <%= form.text_field :vorname, id: :loser_vorname %>
  </div>

  <div class="field">
    <%= form.label :nachname %>
    <%= form.text_field :nachname, id: :loser_nachname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/losers/edit.html.erb
<h1>Editing Loser</h1>

<%= render 'form', loser: @loser %>

<%= link_to 'Show', @loser %> |
<%= link_to 'Back', losers_path %>

app/views/losers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Losers</h1>

<table>
  <thead>
    <tr>
      <th>Vorname</th>
      <th>Nachname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @losers.each do |loser| %>
      <tr>
        <td><%= loser.vorname %></td>
        <td><%= loser.nachname %></td>
        <td><%= link_to 'Show', loser %></td>
        <td><%= link_to 'Edit', edit_loser_path(loser) %></td>
        <td><%= link_to 'Destroy', loser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loser', new_loser_path %>

app/views/losers/new.html.erb
<h1>New Loser</h1>

<%= render 'form', loser: @loser %>

<%= link_to 'Back', losers_path %>

app/views/losers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vorname:</strong>
  <%= @loser.vorname %>
</p>

<p>
  <strong>Nachname:</strong>
  <%= @loser.nachname %>
</p>

<%= link_to 'Edit', edit_loser_path(@loser) %> |
<%= link_to 'Back', losers_path %>